[BIN SPECS]

; number of bins
nbin = 20
; smallest aerosol RADIUS (nm)
radius_1 = 1
; largest aerosol RADIUS (nm)
radius_N = 7000

[SPECIES]
; active species
organic = False
dust = True
sulfate = False
blackcarbon = False
blackcarbon_insoluble = False
seasalt = False
nitrate = False

[RANGE SPECS]
; Set false if bins and ranges are equal (traditional sectional scheme)
ranges = True
; chemistry range BOUNDS (nm)
; These are soft bounds, the actual values will be adjusted to the nearest bin
; Suggested values:
; 0.5nm - 5nm     : Nucleation
; 5nm - 50 nm     : Aitken
; 50nm - 500 nm   : Accumulation
; 500nm - ...	   : Coarse
range_bounds = 0.5,5,50,500,10000

; size range for each species (to be researched somewhere.. :D)
; These are soft bounds, the actual values will be adjusted to the nearest range bounds
; THE SPECIES RANGE BOUNDS HAVE TO BE EQUAL TO VALUES IN THE range_bounds
; bounds have to be set even if species is not active
organic_range = 0.5,10000
dust_range = 50,10000
sulfate_range = 0.5,10000
blackcarbon_range = 5,10000
blackcarbon_insoluble_range = 0.5,5
seasalt_range = 5,10000
nitrate_range = 5,10000


