[BIN SPECS]

; number of bins
nbin = 20
; smallest aerosol RADIUS (nm)
radius_1 = 1
; largest aerosol RADIUS (nm)
radius_N = 7000

[RANGE SPECS]
; chemical ranges, if set to False: ranges = bins
ranges = True
; chemistry range BOUNDS (nm)
; These are soft bounds, the actual values will be adjusted to the nearest bin
; Suggested values:
; 0.5nm - 5nm     : Nucleation
; 5nm - 50 nm     : Aitken
; 50nm - 500 nm   : Accumulation
; 500nm - ...	   : Coarse
range_bounds = 0.5,5,50,500,10000

;=================================================================================
; SPECIES
;=================================================================================
; Species bounds are soft bounds, the values will be adjusted to the nearest range
; bounds.
; Species bounds have to be equal to the values in [RANGE SPECS] range_bounds!
; New species and their properties can be added as a new section and will be
; converted to tracers by bin_config.py
; If e.g. a species has different composition for different bins, separate entries are
; needed. These should have different names in the [] but the same short and long names
; density and molecular weight are from oslo_aero_share.F90

[ORGANIC]
active = False
short_name = OA
species_type = s-organic
long_name = Organic aerosol
range_bounds = 0.5,10000
composition = C
density = 1500.0
molecular_weight = 168.2
mixed = True
kappa = 0.06

[DUST]
active = True
short_name = DU
species_type = dust
long_name = Dust aerosol
range_bounds = 50,10000
composition = AlSiO5
density = 2600.0
molecular_weight = 135.0
mixed = True
kappa = 0.0

[SULFATE]
active = False
short_name = SO4
species_type = sulfate
long_name = Sulfate aerosol
range_bounds = 0.5,10000
; H2SO4??
composition = NH4SO4
density = 1769.0
molecular_weight = 132.0
mixed = True
kappa = 0.6

[BLACKCARBON]
active = False
short_name = BC
species_type = black-c
long_name = Black Carbon aerosol
range_bounds = 5,10000
composition = C
density = 1800.0
molecular_weight = 12.0
mixed = True
kappa = 0.0

[BLACKCARBON INSOLUBLE]
active = False
short_name = BC_is
species_type = black-c
long_name = Insoluble Black Carbon aerosol
range_bounds = 0.5,5
composition = C
density = 1800.0
molecular_weight = 12.0
mixed = False
kappa = 0.0

[SEASALT]
active = False
short_name = SS
species_type = seasalt
long_name = Seasalt aerosol
range_bounds = 5,10000
composition = NaCl
density = 2200.0
molecular_weight = 58.44
mixed = True
kappa = 1.0

[NITRATE]
active = False
short_name = NO3
species_type = nitrate
long_name = Nitrate aerosol
range_bounds = 5,10000
; composition??
composition = NO3
density = 0.0
molecular_weight = 0.0
mixed = True
kappa = 0.0


; [Some new species]
; active = True/False
; short_name = XX
; long_name = some name
; range_bounds = X,X radius, um
; composition = XX
; density = XX [kg/m3]
; molecular_weight = XX [kg/kmol]
; mixed = True/False
; hygroscopicity_param = 0.