[BIN SPECS]

; number of bins
nbin = 20
; smallest aerosol RADIUS (nm)
radius_1 = 1
; largest aerosol RADIUS (nm)
radius_N = 7000

[RANGE SPECS]
; chemical ranges, if set to False: ranges = bins
ranges = True
; chemistry range BOUNDS (nm)
; These are soft bounds, the actual values will be adjusted to the nearest bin
; Suggested values:
; 0.5nm - 5nm     : Nucleation
; 5nm - 50 nm     : Aitken
; 50nm - 500 nm   : Accumulation
; 500nm - ...	   : Coarse
range_bounds = 0.5,5,50,500,10000

;=================================================================================
; SPECIES
;=================================================================================
; Species bounds are soft bounds, the values will be adjusted to the nearest range
; bounds.
; Species bounds have to be equal to the values in [RANGE SPECS] range_bounds!
; New species and their properties can be added as a new section and will be
; converted to tracers by bin_config.py
; If e.g. a species has different composition for different bins, separate entries are
; needed. These should have different names in the [] but the same short and long names

[ORGANIC]
active = True
short_name = OA
long_name = Organic aerosol
range_bounds = 0.5,10000
composition = C
mixed = True

[DUST]
active = True
short_name = DU
long_name = Dust aerosol
range_bounds = 50,10000
composition = AlSiO5
mixed = True

[SULFATE]
active = True
short_name = SO4
long_name = Sulfate aerosol
range_bounds = 0.5,10000
; H2SO4??
composition = NH4SO4
mixed = False

[BLACKCARBON]
active = True
short_name = BC
long_name = Black Carbon aerosol
range_bounds = 5,10000
composition = C
mixed = True

[BLACKCARBON INSOLUBLE]
active = True
short_name = BC_is
long_name = Insoluble Black Carbon aerosol
range_bounds = 0.5,5
composition = C
mixed = False

[SEASALT]
active = True
short_name = SS
long_name = Seasalt aerosol
range_bounds = 5,10000
composition = NaCl
mixed = True

[NITRATE]
active = True
short_name = NO3
long_name = Nitrate aerosol
range_bounds = 5,10000
; composition??
composition = NO3
mixed = True
